### ISSUE TITLE
Project tests don't actually test data import

### ISSUE THREAD

**Issue by S4lt5** [cisagov/assessment-data-import-lambda#39]
As part of a general 'get well' effort I've created "Expected outputs" @ https://github.com/cisagov/pen-test-portal/tree/schema-change/ptportal/tests and will be adding those artifacts to this project to make sure that at a basic level, the ADI program can actually handle the output of the files being produced by PTP.

Additionally, the new "v2" schema is not handled here, so I am going to setup a PR to handle that specifically with some basic accompanying tests.

**Comment by mcdonnnj** [comment]
This project does not process Pen Test Portal data.
