### ISSUE TITLE
Some of the list comprehension funcs are hard to read

### ISSUE THREAD

**Issue by S4lt5** [cisagov/assessment-data-import-lambda#40]
I'm a big fan of list comprehension, but:

https://github.com/cisagov/assessment-data-import-lambda/blob/767141c276494879db0f73f9fe2465f0250c38cc/adi/assessment_data_import.py#L155-L173

is difficult to make sense of at first glance :)

155-173 could probably replaced with a single pass through the missing fields and be a little clearer to the reader

**Comment by mcdonnnj** [comment]
Feel free to make a pull request for review if you think another implementation would be better but I do not think anyone on our development team has an issue with how it is currently implemented.
